name: Trigger ZIP creation in Repo B

on:
  push:
    paths:
      - 'acm/**/*.pdf'
      - 'fbos/**/*.pdf'
      - 'rac/**/*.pdf'
      - 'frc/**/*.pdf'
      - 'herc/**/*.pdf'

jobs:
  trigger-zipfiles-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Repo B workflow via GitHub API
        env:
          REPO_B: bufoes/zipfiles
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/$REPO_B/actions/workflows/create-zip.yml/dispatches \
            -d '{"ref":"main"}'
