name: Create ZIPs from Repo A content

on:
  workflow_dispatch: # triggered manually or from Repo A

jobs:
  create-zips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo B (self)
        uses: actions/checkout@v4

      - name: Clone Repo A
        env:
          REPO_A: https://x-access-token:${{ secrets.PAT }}@github.com/bufoes/bufoes.github.io.git
        run: |
          git clone $REPO_A repo-a

      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Create ZIPs for folders
        run: |
          mkdir -p zips
          for dir in acm fbos rac frc herc; do
            if [ -d "repo-a/$dir" ]; then
              echo "Zipping $dir"
              zip -r "zips/$dir.zip" "repo-a/$dir"
            else
              echo "$dir does not exist in repo-a, skipping"
            fi
          done

      - name: Commit and push ZIPs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add zips/*.zip

          if git diff --cached --quiet; then
            echo "No changes in ZIP files"
          else
            git commit -m "Update ZIPs from Repo A content"
            git push
          fi
